[project]
name = "horny-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "blessed>=1.24.0",
    "numpy>=2.3.4",
]

[project.scripts]
main = "horny_app.main:main"

[tool.uv]
package = true
